### ISSUE TITLE
issue with data generator

### ISSUE THREAD

**Issue by Prashannakhanal** [KunalVaidya99/Music-Genre-Classification#1]
train_dir = "/content/gdrive/My Drive/spectrograms3sec/train/"
train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(train_dir,target_size=(288,432),color_mode="rgba",class_mode='categorical',batch_size=128)

validation_dir = "/content/gdrive/My Drive/spectrograms3sec/test/"
vali_datagen = ImageDataGenerator(rescale=1./255)
vali_generator = vali_datagen.flow_from_directory(validation_dir,target_size=(288,432),color_mode='rgba',class_mode='categorical',batch_size=128)
 output: Found 0 images belonging to 3 classes.
             Found 0 images belonging to 3 classes.
why is so?

**Comment by KunalVaidya99** [comment]
Check if you have images in the directory you have used for DataGenerator

**Comment by Prashannakhanal** [comment]
directory = "/content/drive/MyDrive/spectrograms3sec/train/"
for g in genre:
  filenames = os.listdir(os.path.join(directory,f"{g}"))
  random.shuffle(filenames)
  test_files = filenames[0:100]

  for f in test_files:

    shutil.move(directory + f"{g}"+ "/" + f,"/content/drive/MyDrive/spectrograms3sec/test/" + f"{g}")
when i run this code there was neither any output nor any error .

**Comment by Prashannakhanal** [comment]
i thought above code will automatically put the data inside the train  directory

**Comment by Prashannakhanal** [comment]
i need ur help. also the method u have used is exactly what i had thought (input as mel spetrogram to train the model). that's why i followed ur code.
