### ISSUE TITLE
NameError: name 'X_test' is not defined

### ISSUE THREAD

**Issue by Prashannakhanal** [KunalVaidya99/Music-Genre-Classification#3]
preds = model.evaluate(x=X_test,y=Y_test)
print(preds[1])
print(preds[2])
when i ran this code it showed 
NameError: name 'X_test' is not defined
how to solve it

**Comment by KunalVaidya99** [comment]
Check if you have defined X_test in your code.

**Comment by Prashannakhanal** [comment]
sir i am using ur code .and u havent defined any x_test in ur code

**Comment by Prashannakhanal** [comment]
[image: Screenshot (27).png]

**Comment by Prashannakhanal** [comment]
sir the code in above figure is yours. but when i tried to run the same
last code  it said[image: Screenshot (24).png]

**Comment by KunalVaidya99** [comment]
I guess that part of code is not relevant,  you can use evaluate_generator for this as you have used ImageDataGenerator for training

**Comment by Prashannakhanal** [comment]
Thanks, I'll check it out.

**Comment by Prashannakhanal** [comment]
sir can u prove me code for generating confusion matrix ,model accuracy,
model loss( diagram),loss vs epoch (diagram) etc
i would really appreciate it

**Comment by KunalVaidya99** [comment]
https://stackoverflow.com/questions/41908379/keras-plot-training-validation-and-test-set-accuracy. Check this out
